---
title: "ECS530: Spatial data analysis C"
author: "Roger Bivand"
date: "Wednesday 16 November 2022"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 2
theme: united
bibliography: ecs530_22.bib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, paged.print=FALSE)
```

### Copyright

All the material presented here, to the extent it is original, is available under [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/). 

## Plan for 16-18 November 2022

### Wednesday 16/11

09:00-10:00 Spatio-temporal cubes, juridicial change (exercises)

10:15-11:15 Global and local spatial autocorrelation 

11:15-12:00 Data puzzles (support)

13:00-14:15 Global and local spatial autocorrelation (exercises)

14:30-15:30 Residual autocorrelation (exercises)

### Thursday 17/11

09:00-10:15 Spatial autocorrelation and machine learning

10:30-11:30 Point pattern analysis

11:30-12:00 Point pattern analysis (exercises)

13:00-14:30 Transport, networks, transmission

14:45-15:45 Transport, networks, transmission (exercises)


### Friday 18/11

Depending on the number of participants wishing to present project outlines (about 25 minutes, 10-15 minutes presentation, 10-15 minutes discussion, the number of slots may vary.

09:00-12:00 Presentation of up to six project outlines, with 20 min. break.

12:30-15:30 Presentation of up to six project outlines, with 20 min. break.

15:30-16:00 Round-up and feedback


## Global and local spatial autocorrelation

https://r-spatial.org/book/15-Measures.html
https://edzer.github.io/sdsr_exercises/14.html
https://edzer.github.io/sdsr_exercises/15.html

https://rsbivand.github.io/ECS530_h21/ECS530_211117.html

https://geodacenter.github.io/documentation.html

https://pysal.org/esda/


## Data puzzles

@doi:10.1177/1471082X20967158, https://github.com/rsbivand/survival_katrina, @Bivand_2017, https://r-spatial.org/book/16-SpatialRegression.html


## Residual autocorrelation

https://pysal.org/spreg/

https://r-spatial.org/book/16-SpatialRegression.html
https://edzer.github.io/sdsr_exercises/16.html

https://r-spatial.org/book/17-Econometrics.html
https://edzer.github.io/sdsr_exercises/17.html

@math9111276 and https://doi.org/10.1016/j.regsciurbeco.2014.03.002 on tests

